

 spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: ANsaRI5%$
  application:
    name: ADDRESS-SERVICE



 server:
   port: 8091

 eureka:
   client:
     service-url:
       defaultZone: http://localhost:8765/eureka/
